theme: jekyll-theme-hacker


title: Ether Capital
tagline: Ether Capital strives to be the single biggest Ether (ETH) accumulator in the capital markets.

twitter:
  username: ethcap
  card: summary

logo: ./ethcap.jpeg

description: <a href="https://www.ethcap.co/">Ether Capital</a> strives to be the single biggest Ether (ETH) accumulator in the capital markets.

show_downloads: false
google_analytics: G-GWL7J1CHCK